#baseurl: "/jekyll-test"
#url: "https://davilaellie.github.io/"
exclude: ['README.md']
remote_theme: pmarsceill/just-the-docs

heading_anchors: true

logo: "/ohlogo.jpg"

permalink: pretty

footer_content:

search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  
# Define Jekyll collections
collections:
  # Define a collection named "docs", its documents reside in the "_docs" directory
  docs:
 
    eir: 
      permalink: "/docs/eir/"
      output: true
    eml:
      permalink: "/docs/eml/"
      output: true





      
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

back_to_top: true
back_to_top_text: "Back to top"

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

files: true
uploads: true

plugins:
  - jekyll-seo-tag




